### ISSUE TITLE
`connection_stress_and_reconnect` timeouts sometimes

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#832]
<details>
Failure:

    […]
    2022-05-11T12:13:14.310924Z  INFO nimiq_network_libp2p::network: Connection closed because cause=Connection error: I/O error: connection is closed
    2022-05-11T12:13:14.313471Z DEBUG nimiq_network_libp2p::discovery::behaviour: addresses_of_peer peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp addresses=[]
    2022-05-11T12:13:14.313710Z DEBUG nimiq_network_libp2p::network: Dialing peer peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp
    2022-05-11T12:13:14.318793Z DEBUG nimiq_network_libp2p::network: Incoming connection address=/memory/4522808024196767701 listen_address=/memory/986765391492110336
    2022-05-11T12:13:14.323753Z DEBUG nimiq_network_libp2p::network: DHT bootstrap successful result=BootstrapOk { peer: PeerId("1AZx8hzrq2sVUywZgLL2YewP4KVDjYhxuXECmJmaSKLcnv"), num_remaining: 1 }
    2022-05-11T12:13:14.339581Z DEBUG nimiq_network_libp2p::connection_pool::behaviour: Connection established peer_id=12D3KooWJWrZGJJbhXQnfwxBYqFywc9inEQbTE11wMGTYSFJffGx address=/memory/4522808024196767701 endpoint=Listener { local_addr: "/memory/986765391492110336", send_back_addr: "/memory/4522808024196767701" }
    2022-05-11T12:13:14.339710Z DEBUG nimiq_network_libp2p::connection_pool::behaviour: Maintaining peers peer_ids=connected=14, dialing=0, failed=0, down=0 addresses=connected=15, dialing=0, failed=0, down=0
    2022-05-11T12:13:14.339738Z DEBUG nimiq_network_libp2p::network: Connection established peer_id=12D3KooWJWrZGJJbhXQnfwxBYqFywc9inEQbTE11wMGTYSFJffGx endpoint=Listener { local_addr: "/memory/986765391492110336", send_back_addr: "/memory/4522808024196767701" } connections=1
    2022-05-11T12:13:14.339853Z  INFO nimiq_network_libp2p::network: Peer joined peer_id=12D3KooWJWrZGJJbhXQnfwxBYqFywc9inEQbTE11wMGTYSFJffGx
    2022-05-11T12:13:14.340138Z DEBUG nimiq_network_libp2p::connection_pool::behaviour: Connection established peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp address=/memory/986765391492110336/p2p/12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp endpoint=Dialer { address: "/memory/986765391492110336/p2p/12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp", role_override: Dialer }
    2022-05-11T12:13:14.340322Z DEBUG nimiq_network_libp2p::connection_pool::behaviour: Maintaining peers peer_ids=connected=14, dialing=0, failed=0, down=0 addresses=connected=16, dialing=0, failed=0, down=0
    2022-05-11T12:13:14.340346Z DEBUG nimiq_network_libp2p::network: Connection established peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp endpoint=Dialer { address: "/memory/986765391492110336/p2p/12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp", role_override: Dialer } connections=1
    2022-05-11T12:13:14.340464Z DEBUG nimiq_network_libp2p::network: Saving peer peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp address=/memory/986765391492110336/p2p/12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp
    2022-05-11T12:13:14.340716Z  INFO nimiq_network_libp2p::network: Peer joined peer_id=12D3KooWHEoYACm5nzsVqaMArr3oyWJ1vGz2AqopxvH4vVJRpXVp
    2022-05-11T12:13:14.344704Z DEBUG nimiq_network_libp2p::discovery::handler: Inbound and outbound connected. Performing handshake
    2022-05-11T12:13:14.351136Z DEBUG nimiq_network_libp2p::discovery::handler: Inbound and outbound connected. Performing handshake
    2022-05-11T12:13:14.352491Z DEBUG nimiq_network_libp2p::network: Received identity peer_id=12D3KooWJWrZGJJbhXQnfwxBYqFywc9inEQbTE11wMGTYSFJffGx address=/memory/8371357920768826581 info=IdentifyInfo { public_key: Ed25519(PublicKey(compressed): 813cd395a67caae55140e3119d1b947de2f5b97cb1937ca2d5ecf323d412e775), protocol_version: "/albatross/2.0", agent_version: "rust-libp2p/0.35.0", listen_addrs: ["/memory/3039899063687907558"], protocols: ["/ipfs/kad/1.0.0", "/nimiq/discovery/0.0.1", "/meshsub/1.1.0", "/meshsub/1.0.0", "/ipfs/id/1.0.0", "/ipfs/id/push/1.0.0", "/nimiq/reqres/0.0.1"], observed_addr: "/memory/8371357920768826581" }
    thread 'connections_stress_and_reconnect' panicked at 'assertion failed: `(left == right)`
      left: `14`,
     right: `13`', network-libp2p/tests/network.rs:296:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    failures:
        connections_stress_and_reconnect

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 6 filtered out; finished in 4.57s

</details>

Timeout:

```
running 1 test
test connections_stress_and_reconnect has been running for over 60 seconds
```

**Comment by jsdanielh** [comment]
Already fixed by #828.

**Comment by hrxi** [comment]
Timeout still happens unfortunately. It took a long while to reproduce it, maybe it only happens under load?
